# build environment
FROM node:19

RUN mkdir /app

WORKDIR /app

COPY package*.json ./

RUN npm install -g serve

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

CMD ["npx", "serve", "build"]