version: '1.0.0'
services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
    depends_on:
      - vestaDb
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    tty: true
  vestaDb:
    container_name: vestaDb
    image: postgres
    restart: always
    expose:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: vestaDb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}